In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("Downloads/Breast_Cancer.csv")
data

Age   Race Marital Status T Stage  N Stage 6th Stage  \
0      68  White        Married       T1      N1       IIA   
1      50  White        Married       T2      N2      IIIA   
2      58  White       Divorced       T3      N3      IIIC   
3      58  White        Married       T1      N1       IIA   
4      47  White        Married       T2      N1       IIB   
...   ...    ...            ...      ...     ...       ...   
4019   62  Other        Married       T1      N1       IIA   
4020   56  White       Divorced       T2      N2      IIIA   
4021   68  White        Married       T2      N1       IIB   
4022   58  Black       Divorced       T2      N1       IIB   
4023   46  White        Married       T2      N1       IIB   

                  differentiate Grade   A Stage  Tumor Size Estrogen Status  \
0         Poorly differentiated     3  Regional           4        Positive   
1     Moderately differentiated     2  Regional          35        Positive   
2     Moderately differentiated     2  Regional          63        Positive   
3         Poorly differentiated     3  Regional          18        Positive   
4         Poorly differentiated     3  Regional          41        Positive   
...                         ...   ...       ...         ...             ...   
4019  Moderately differentiated     2  Regional           9        Positive   
4020  Moderately differentiated     2  Regional          46        Positive   
4021  Moderately differentiated     2  Regional          22        Positive   
4022  Moderately differentiated     2  Regional          44        Positive   
4023  Moderately differentiated     2  Regional          30        Positive   

     Progesterone Status  Regional Node Examined  Reginol Node Positive  \
0               Positive                      24                      1   
1               Positive                      14                      5   
2               Positive                      14                      7   
3               Positive                       2                      1   
4               Positive                       3                      1   
...                  ...                     ...                    ...   
4019            Positive                       1                      1   
4020            Positive                      14                      8   
4021            Negative                      11                      3   
4022            Positive                      11                      1   
4023            Positive                       7                      2   

      Survival Months Status  
0                  60  Alive  
1                  62  Alive  
2                  75  Alive  
3                  84  Alive  
4                  50  Alive  
...               ...    ...  
4019               49  Alive  
4020               69  Alive  
4021               69  Alive  
4022               72  Alive  
4023              100  Alive  

[4024 rows x 16 columns]

In [3]:
data.isnull().sum()

Age                       0
Race                      0
Marital Status            0
T Stage                   0
N Stage                   0
6th Stage                 0
differentiate             0
Grade                     0
A Stage                   0
Tumor Size                0
Estrogen Status           0
Progesterone Status       0
Regional Node Examined    0
Reginol Node Positive     0
Survival Months           0
Status                    0
dtype: int64

In [4]:
data["Grade"].replace(' anaplastic; Grade IV',np.nan,True)

In [5]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(data.iloc[:,7:8])
data.iloc[:,7:8]=imputer.transform(data.iloc[:,7:8])

C:\Users\LENOVO\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [6]:
#ENCODING THE COLUMNS
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
breast=['Race','Marital Status','N Stage','6th Stage','differentiate','A Stage','Estrogen Status','Progesterone Status','Status']
data[breast]=data[breast].apply(le.fit_transform)
data.head()

Age  Race  Marital Status T Stage   N Stage  6th Stage  differentiate  \
0   68     2               1       T1        0          0              1   
1   50     2               1       T2        1          2              0   
2   58     2               0       T3        2          4              0   
3   58     2               1       T1        0          0              1   
4   47     2               1       T2        0          1              1   

   Grade  A Stage  Tumor Size  Estrogen Status  Progesterone Status  \
0    3.0        1           4                1                    1   
1    2.0        1          35                1                    1   
2    2.0        1          63                1                    1   
3    3.0        1          18                1                    1   
4    3.0        1          41                1                    1   

   Regional Node Examined  Reginol Node Positive  Survival Months  Status  
0                      24                      1               60       0  
1                      14                      5               62       0  
2                      14                      7               75       0  
3                       2                      1               84       0  
4                       3                      1               50       0

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data.iloc[:,3:4]=le.fit_transform(data.iloc[:,3:4])
data

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Age  Race  Marital Status  T Stage   N Stage  6th Stage  differentiate  \
0      68     2               1         0        0          0              1   
1      50     2               1         1        1          2              0   
2      58     2               0         2        2          4              0   
3      58     2               1         0        0          0              1   
4      47     2               1         1        0          1              1   
...   ...   ...             ...       ...      ...        ...            ...   
4019   62     1               1         0        0          0              0   
4020   56     2               0         1        1          2              0   
4021   68     2               1         1        0          1              0   
4022   58     0               0         1        0          1              0   
4023   46     2               1         1        0          1              0   

      Grade  A Stage  Tumor Size  Estrogen Status  Progesterone Status  \
0       3.0        1           4                1                    1   
1       2.0        1          35                1                    1   
2       2.0        1          63                1                    1   
3       3.0        1          18                1                    1   
4       3.0        1          41                1                    1   
...     ...      ...         ...              ...                  ...   
4019    2.0        1           9                1                    1   
4020    2.0        1          46                1                    1   
4021    2.0        1          22                1                    0   
4022    2.0        1          44                1                    1   
4023    2.0        1          30                1                    1   

      Regional Node Examined  Reginol Node Positive  Survival Months  Status  
0                         24                      1               60       0  
1                         14                      5               62       0  
2                         14                      7               75       0  
3                          2                      1               84       0  
4                          3                      1               50       0  
...                      ...                    ...              ...     ...  
4019                       1                      1               49       0  
4020                      14                      8               69       0  
4021                      11                      3               69       0  
4022                      11                      1               72       0  
4023                       7                      2              100       0  

[4024 rows x 16 columns]

In [8]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1:]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [10]:
#LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=1)
classifier.fit(x_train,y_train)

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=1)

In [11]:
y_pred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[655   9]
 [ 85  56]]


In [12]:
ac=accuracy_score(y_test,y_pred)
ac

0.8832298136645963

In [13]:
#SUPPORT VECTOR MACHNE
from sklearn.svm import SVC
classifier=SVC(kernel="linear",random_state=1)
classifier.fit(x_train,y_train)

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear', random_state=1)

In [14]:
y_pred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[656   8]
 [ 87  54]]


In [15]:
ac=accuracy_score(y_test,y_pred)
ac

0.8819875776397516

In [16]:
#DECISION TREE
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(random_state=1)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(random_state=1)

In [17]:
y_pred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[597  67]
 [ 72  69]]


In [18]:
ac=accuracy_score(y_test,y_pred)
ac

0.8273291925465839

In [19]:
#RANDOM FOREST 
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=3500,random_state=1)
classifier.fit(x_train,y_train)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_68528\3290026445.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(x_train,y_train)


RandomForestClassifier(n_estimators=3500, random_state=1)

In [20]:
y_pred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[650  14]
 [ 78  63]]


In [21]:
ac=accuracy_score(y_test,y_pred)
ac

0.8857142857142857

In [22]:
#K NEAREST NEIGHBORS
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [23]:
y_pred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[648  16]
 [ 86  55]]


C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [24]:
ac=accuracy_score(y_test,y_pred)
ac

0.8732919254658386

In [25]:
#NAIVE BAYS
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [26]:
y_pred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[578  86]
 [ 82  59]]


In [27]:
ac=accuracy_score(y_test,y_pred)
ac

0.7913043478260869